<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-07T11:57:00 IST" name="Suite" finished-at="2024-11-07T11:57:13 IST" duration-ms="12977">
    <groups>
      <group name="Regression">
        <method signature="AccountRegistrationTC.verify_account_registration()[pri:0, instance:testCases.AccountRegistrationTC@4de025bf]" name="verify_account_registration" class="testCases.AccountRegistrationTC"/>
        <method signature="LoginTC.validateLogin_Singleton()[pri:1, instance:testCases.LoginTC@5c1bd44c]" name="validateLogin_Singleton" class="testCases.LoginTC"/>
      </group> <!-- Regression -->
      <group name="sanity">
        <method signature="AccountRegistrationTC.verify_account_registration()[pri:0, instance:testCases.AccountRegistrationTC@4de025bf]" name="verify_account_registration" class="testCases.AccountRegistrationTC"/>
        <method signature="LoginTC.validate_login()[pri:0, instance:testCases.LoginTC@5c1bd44c]" name="validate_login" class="testCases.LoginTC"/>
        <method signature="LoginTC.validateLogin_Singleton()[pri:1, instance:testCases.LoginTC@5c1bd44c]" name="validateLogin_Singleton" class="testCases.LoginTC"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2024-11-07T11:57:00 IST" name="Test" finished-at="2024-11-07T11:57:13 IST" duration-ms="12977">
      <class name="testCases.LoginTC">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String)[pri:0, instance:testCases.LoginTC@5c1bd44c]" started-at="2024-11-07T11:57:09 IST" name="setUp" finished-at="2024-11-07T11:57:13 IST" duration-ms="4428" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validate_login()[pri:0, instance:testCases.LoginTC@5c1bd44c]" started-at="2024-11-07T11:57:13 IST" name="validate_login" finished-at="2024-11-07T11:57:13 IST" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[validate_login test failed due to an exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: validate_login test failed due to an exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.LoginTC.validate_login(LoginTC.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_login -->
        <test-method signature="validateLogin_Singleton()[pri:1, instance:testCases.LoginTC@5c1bd44c]" started-at="2024-11-07T11:57:13 IST" name="validateLogin_Singleton" finished-at="2024-11-07T11:57:13 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[validateLogin_Singleton test failed due to an exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: validateLogin_Singleton test failed due to an exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.LoginTC.validateLogin_Singleton(LoginTC.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin_Singleton -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.LoginTC@5c1bd44c]" started-at="2024-11-07T11:57:13 IST" name="tearDown" finished-at="2024-11-07T11:57:13 IST" duration-ms="215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.LoginTC -->
      <class name="testCases.AccountRegistrationTC">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String)[pri:0, instance:testCases.AccountRegistrationTC@4de025bf]" started-at="2024-11-07T11:57:00 IST" name="setUp" finished-at="2024-11-07T11:57:05 IST" duration-ms="4719" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verify_account_registration()[pri:0, instance:testCases.AccountRegistrationTC@4de025bf]" started-at="2024-11-07T11:57:05 IST" name="verify_account_registration" finished-at="2024-11-07T11:57:08 IST" duration-ms="3252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_account_registration -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.AccountRegistrationTC@4de025bf]" started-at="2024-11-07T11:57:08 IST" name="tearDown" finished-at="2024-11-07T11:57:09 IST" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.AccountRegistrationTC -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
